# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lx < Formula
  desc "A beautiful LaTeX notes manager"
  homepage "https://github.com/kamal-hamza/lx-cli"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kamal-hamza/lx-cli/releases/download/v0.1.5/lx_0.1.5_darwin_amd64.tar.gz"
      sha256 "a0445231b4bc56d5b4763d3839fc5b8eb805e829d48b77ed991be00ac49735de"

      def install
        bin.install "lx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kamal-hamza/lx-cli/releases/download/v0.1.5/lx_0.1.5_darwin_arm64.tar.gz"
      sha256 "8761796422dc99f7659d38aa3a8c7c6110b620ed6f72324369d87122b55cfea5"

      def install
        bin.install "lx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamal-hamza/lx-cli/releases/download/v0.1.5/lx_0.1.5_linux_amd64.tar.gz"
      sha256 "14fa4177ba99d3e485f1326b325902895bf4af3d88fe0ec235a0cbc7d0e6c335"
      def install
        bin.install "lx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamal-hamza/lx-cli/releases/download/v0.1.5/lx_0.1.5_linux_arm64.tar.gz"
      sha256 "823170576916ea9d7980ceae9964ba9e240e4601d791346a95654efeee29f376"
      def install
        bin.install "lx"
      end
    end
  end
end
