# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lx < Formula
  desc "A beautiful LaTeX notes manager"
  homepage "https://github.com/kamal-hamza/lx-cli"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kamal-hamza/lx-cli/releases/download/v0.1.4/lx_0.1.4_darwin_amd64.tar.gz"
      sha256 "8b25256e359a2a8af462e53ac986aff57bef778765cdab6a97053edf70bb4052"

      def install
        bin.install "lx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kamal-hamza/lx-cli/releases/download/v0.1.4/lx_0.1.4_darwin_arm64.tar.gz"
      sha256 "8ec5ff2916f1c787742c168f59e03732a8cef94a3e810457a7330979da4097dc"

      def install
        bin.install "lx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamal-hamza/lx-cli/releases/download/v0.1.4/lx_0.1.4_linux_amd64.tar.gz"
      sha256 "c370e532b1f2b13c97f67b02188a5fe825dda6f173bbaf11e466b3f20d3ef503"
      def install
        bin.install "lx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamal-hamza/lx-cli/releases/download/v0.1.4/lx_0.1.4_linux_arm64.tar.gz"
      sha256 "3fa8df97721bf73681149aeea6a9ae974312d159403397d9f50e72e391f18277"
      def install
        bin.install "lx"
      end
    end
  end
end
