# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lx < Formula
  desc "A beautiful LaTeX notes manager"
  homepage "https://github.com/kamal-hamza/lx-cli"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kamal-hamza/lx-cli/releases/download/v0.1.2/lx_0.1.2_darwin_amd64.tar.gz"
      sha256 "ea229bfdab26dd4a296a5ddb44dd7a314bfd2e836c9be43e3778abddc163a130"

      def install
        bin.install "lx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kamal-hamza/lx-cli/releases/download/v0.1.2/lx_0.1.2_darwin_arm64.tar.gz"
      sha256 "82850a559a9e2a3e86af1b5f002c1c172bc07fcca285834398937c06c2cb7eac"

      def install
        bin.install "lx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamal-hamza/lx-cli/releases/download/v0.1.2/lx_0.1.2_linux_amd64.tar.gz"
      sha256 "982d901bf35cca2bc3b6150cd32a21a74495615467808d093ba89db4919082de"
      def install
        bin.install "lx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamal-hamza/lx-cli/releases/download/v0.1.2/lx_0.1.2_linux_arm64.tar.gz"
      sha256 "951d3923181410fbc91357f7fe67a37d66d2d70ae68158072313bbf0d255f2bc"
      def install
        bin.install "lx"
      end
    end
  end
end
